### ISSUE TITLE
play-json integration without play plugin

### ISSUE THREAD

**Issue by francisdb** [ReactiveMongo/ReactiveMongo#268] opened 2015-02-03 11:15 UTC
Would be nice if you could release the play-json integration (JSONCollection) separately from the play plugin. Play-json is released separately and changes much less often.

My use case is using reactivemongo with play-json and akka-http

This would also open the door for other json library integrations.

**Comment by duncancrawford** [comment] 2015-02-03 11:29
@francisdb we had the same requirement so did it ourselves and you can find it here https://github.com/hmrc/reactivemongo-json

**Comment by cchantep** [comment] 2015-04-03 08:54
(Duplicate of https://github.com/ReactiveMongo/Play-ReactiveMongo/issues/103 )

**Closed** 2015-06-15 23:49 UTC
