### ISSUE TITLE
find with tailable and awaitData results in super-fast cursor creation

### ISSUE THREAD

**Issue by bradrust** [ReactiveMongo/ReactiveMongo#1006] opened 2020-11-22 19:07 UTC
### ReactiveMongo Version (0.10.5, 0.11.6 / etc)
"org.reactivemongo" %% "reactivemongo" % "1.0.0",
"org.reactivemongo" %% "play2-reactivemongo" % "1.0.0-play28",
"org.reactivemongo" %% "reactivemongo-akkastream" % "1.0.0",

### MongoDB version 
db version v4.4.0

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Darwin Brads-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
openjdk version "11.0.6" 2020-01-14

### Library Dependencies
"org.reactivemongo" %% "reactivemongo" % "1.0.0",
"org.reactivemongo" %% "play2-reactivemongo" % "1.0.0-play28",
"org.reactivemongo" %% "reactivemongo-akkastream" % "1.0.0",
sbt.version=1.3.4
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.2")

### Expected Behavior

1. reading Actor to start a collection.find() with query options tailable and awaitData
2. expect correct "polling" semantics with regard to resource usage of a capped collection 
3. writing Actor to insert documents into capped collection
4. reading Actor to read inserted documents

### Actual Behavior

1. reading Actor starts cursor with tailable and awaitData
2. RM QueryBuilder trace logging yields very fast, repetitive creation of Cursors
3. writing Actor inserts a Document into a capped collection
4. very fast, repetitive cursor creation *stops* at that point and polling semantics operate as expected

### Reproducible Test Case

There are three sequence diagram URL's listed in the README that might be easier to parse what I am seeing...

https://github.com/bradrust/reactivemongo-tailable

### Other systems tested with same results
* appears to fail on Windows 10, Windows 10 under WSL2, Atlas instances (from kubernetes alpine images), MacOS all with either mongodb 4.2+
* appears to happen with RM 1.0.1 as well (tested locally but didn't push build.sbt representing that)

**Comment by cchantep** [comment] 2020-11-22 21:06
Thanks for the efforts, but this tracker is for [confirmed issue](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md), other discussion must happen on the MailingList.

Also, having to use Play integration and "browser" based tests doesn't look like a minimal reproducer for me (and issue due to integration between all that are out of scope).

**Closed by cchantep** 2020-11-22 21:06 UTC
